### ISSUE TITLE
`bypassCache: false` does not work with Modules worker?

### ISSUE THREAD

**Issue by leader22** [cloudflare/kv-asset-handler#274]
If we use this package in `modules` format, it seems to only work with `bypassCache: true`.

Omitting or set to `false` end up with this error.

```
TypeError: Illegal invocation
    at getAssetFromKV (./worker.mjs:287:13)
    at async Object.fetch (./worker.mjs:338:32)

Your worker called response.clone(), but did not read the body of both clones. This is wasteful, as it forces the system to buffer the entire response body in memory, rather than streaming it through. This may cause your worker to be unexpectedly terminated for going over the memory limit. If you only meant to copy the response headers and metadata (e.g. in order to be able to modify them), use `new Response(response.body, response)` instead.
```

This error seems to be occured here.

https://github.com/cloudflare/kv-asset-handler/blob/d1a091e01aa401ea16548153bf0275f1df8b17cd/src/index.ts#L284

To reproduce,

- clone my repo
  - https://github.com/leader22/workers-sites-module-minimum
- fill `account_id`, then `warngler dev`
- visit and see it works
- modify to `bypassCache: false`
  - https://github.com/leader22/workers-sites-module-minimum/blob/7fd3c3b1ee1d126f99517af6785d1129c1618e48/src/index.js#L24:L28
- revist and see error happens

See also this original [issue](https://github.com/cloudflare/miniflare/issues/126) at cloudflare/miniflare.

**Comment by rkusa** [comment]
I think you can fix your demo repo with the following change:

```diff
- waitUntil: ctx.waitUntil,
+ waitUntil: ctx.waitUntil.bind(ctx),
```

At least that is how I was able to fix it in my code when I encountered the `Illegal invocation` error.

**Comment by leader22** [comment]
Thank you for finding a workaround! It is really helpful. ✨ 

And now I noticed README updated and shows usage below.

```js
return await getAssetFromKV(
          {
            request,
            waitUntil(promise) {
              return ctx.waitUntil(promise)
            },
          },
```

It seems we should bind the context by ourselves. 😓 
I hope `getAssetFromKV` accepts `ctx` object itself instead of `waitUntil`.
